name: tornet
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

#############################################################################
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  flutter_riverpod: ^2.6.1
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

#############################################################################
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_lint: ^2.6.5

#############################################################################
flutter:

  uses-material-design: true

  assets:
    - assets/icons/svg/


  fonts:
    - family: Chakra Petch
      fonts:
        - asset: assets/fonts/ChakraPetch-Regular.ttf
          weight: 400
        - asset: assets/fonts/ChakraPetch-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/ChakraPetch-Light.ttf
          weight: 300
        - asset: assets/fonts/ChakraPetch-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/ChakraPetch-Medium.ttf
          weight: 500
        - asset: assets/fonts/ChakraPetch-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/ChakraPetch-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ChakraPetch-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/ChakraPetch-Bold.ttf
          weight: 700
        - asset: assets/fonts/ChakraPetch-BoldItalic.ttf
          weight: 700
          style: italic
          
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
